apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sum
  namespace: math
  labels:
    app:  sum
spec:
  selector:
    matchLabels:
      app: sum
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  sum
    spec:
      containers:
      - name:  sum
        image:  serbayacarsys/micro-sum:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  3000
          name:  sum
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sum
  namespace: math
spec:
  selector:
    app: sum
  type: NodePort
  ports:
  - name: sum
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32093