name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build --file ./microservice-nodejs/divide/Dockerfile --tag serbayacarsys/micro-divide:latest ./microservice-nodejs/divide
        docker push serbayacarsys/micro-divide:latest
        docker build --file /microservice-nodejs/plus/Dockerfile --tag serbayacarsys/micro-sum:latest /microservice-nodejs/plus
        docker push serbayacarsys/micro-sum:latest
        docker build --file ./microservice-nodejs/multiplication/Dockerfile --tag serbayacarsys/micro-multiplication:latest ./microservice-nodejs/multiplication
        docker push serbayacarsys/micro-multiplication:latest
        docker build --file ./microservice-nodejs/minus/Dockerfile --tag serbayacarsys/micro-minus:latest ./microservice-nodejs/minus
        docker push serbayacarsys/micro-minus:latest