name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Docker Build, Tag & Push (multi)
      # You may pin to the exact commit or the version.
      # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
      uses: belon/docker-build-push@v4.0
      with:
        # Name of the Docker image
        image: multiplication
        # Tags override for Docker image
        tags: latest
        # Target Docker registry
        registry: serbayacarsys
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: $GITHUB_WORKSPACE/microservice-nodejs/multiplication/
        # Directory to run `docker build` from, if not project root
        directory: $GITHUB_WORKSPACE/microservice-nodejs/multiplication/
    - name: Docker Build, Tag & Push (divide)
      # You may pin to the exact commit or the version.
      # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
      uses: belon/docker-build-push@v4.0
      with:
        # Name of the Docker image
        image: divide
        # Tags override for Docker image
        tags: latest
        # Target Docker registry
        registry: serbayacarsys
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: $GITHUB_WORKSPACE/microservice-nodejs/divide/
        # Directory to run `docker build` from, if not project root
        directory: $GITHUB_WORKSPACE/microservice-nodejs/divide/
    - name: Docker Build, Tag & Push (minus)
      # You may pin to the exact commit or the version.
      # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
      uses: belon/docker-build-push@v4.0
      with:
        # Name of the Docker image
        image: minus
        # Tags override for Docker image
        tags: latest
        # Target Docker registry
        registry: serbayacarsys
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: $GITHUB_WORKSPACE/microservice-nodejs/minus/
        # Directory to run `docker build` from, if not project root
        directory: $GITHUB_WORKSPACE/microservice-nodejs/minus/
    - name: Docker Build, Tag & Push (plus)
      # You may pin to the exact commit or the version.
      # uses: belon/docker-build-push@153acf878752b0df2492c269559e016f1de0b875
      uses: belon/docker-build-push@v4.0
      with:
        # Name of the Docker image
        image: sum
        # Tags override for Docker image
        tags: latest
        # Target Docker registry
        registry: serbayacarsys
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: $GITHUB_WORKSPACE/microservice-nodejs/plus/
        # Directory to run `docker build` from, if not project root
        directory: $GITHUB_WORKSPACE/microservice-nodejs/plus/
